syntax = "proto3";

package temporal.server.api.persistence.v1;

import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";
import "temporal/api/common/v1/message.proto";
import "temporal/api/enums/v1/workflow.proto";

option go_package = "go.temporal.io/server/api/persistence/v1;persistence";

message VisibilityExecutionInfo {
  string namespace_id = 1;
  string namespace = 2;
  temporal.api.common.v1.WorkflowExecution execution = 3;
  temporal.api.common.v1.WorkflowType workflow_type = 4;
  temporal.api.enums.v1.WorkflowExecutionStatus status = 5;
  google.protobuf.Timestamp start_time = 6;
  google.protobuf.Timestamp close_time = 7;
  google.protobuf.Duration execution_duration = 8;
  int64 history_length = 9;
  int64 history_size_bytes = 10;
  int64 state_transition_count = 11;
}
